import { OrbitInfo, BlankOrbit } from './types';

export const blankOrbits: BlankOrbit[] = [
  {
    radius: 85,
    gravityFactor: 1.6,
    color: '#00d4ff',
    borderStyle: 'dotted',
    borderWidth: 1,
    rotationDuration: 25,
    rotationDirection: -1,
    opacity: 0.2,
  },
  {
    radius: 145,
    gravityFactor: 1.35,
    color: '#00ffaa',
    borderStyle: 'dashed',
    borderWidth: 1,
    rotationDuration: 35,
    rotationDirection: 1,
    opacity: 0.15,
  },
  {
    radius: 205,
    gravityFactor: 1.0,
    color: '#ff00ff',
    borderStyle: 'dashed',
    borderWidth: 2,
    rotationDuration: 45,
    rotationDirection: -1,
    opacity: 0.2,
    className: 'dash-large',
  },
  {
    radius: 275,
    gravityFactor: 0.65,
    color: '#a855f7',
    borderStyle: 'dashed',
    borderWidth: 2,
    rotationDuration: 55,
    rotationDirection: 1,
    opacity: 0.15,
    className: 'dash-xlarge',
  },
  {
    radius: 385,
    gravityFactor: 0.35,
    color: '#6366f1',
    borderStyle: 'dashed',
    borderWidth: 1,
    rotationDuration: 65,
    rotationDirection: -1,
    opacity: 0.1,
  },
];

export const orbitData: OrbitInfo[] = [
  {
    category: 'Identity',
    icon: '👤',
    info: {
      Name: 'Vantuan Le',
      Age: '35 years old',
      Location: 'Vietnam',
      Email: 'tuantuan269dn@gmail.com',
    },
    radius: 120,
    gravityFactor: 1.5,
    color: '#00d4ff',
    borderStyle: 'solid',
    rotationDuration: 20,
    rotationDirection: 1,
  },
  {
    category: 'Technology',
    icon: '💻',
    info: {
      Backend: 'Node.js, .NET, Python, REST APIs',
      Frontend: 'React, Angular, WPF',
      Database: 'DynamoDB, MongoDB, SQL',
      DevOps: 'CI/CD, Azure DevOps, Git',
    },
    radius: 180,
    gravityFactor: 1.2,
    color: '#00ffaa',
    borderStyle: 'dashed',
    rotationDuration: 30,
    rotationDirection: -1,
  },
  {
    category: 'Expertise',
    icon: '🎯',
    info: {
      Architecture: 'Microservices, DDD, CQRS',
      Patterns: 'Event-Driven, Event Sourcing',
      Cloud: 'Azure Functions, Serverless',
      AI: 'Claude Code, GitHub Copilot, ChatGPT',
    },
    radius: 250,
    gravityFactor: 0.8,
    color: '#ff00ff',
    borderStyle: 'dotted',
    rotationDuration: 40,
    rotationDirection: 1,
  },
  {
    category: 'Highlights',
    icon: '🏆',
    info: {
      'AI-Powered Dev Agent': 'Custom AI agents for code automation',
      'Microservices System': 'Event-driven streaming architecture',
      'Workshop Facilitator': 'Team mentorship & training',
    },
    radius: 330,
    gravityFactor: 0.5,
    color: '#a855f7',
    borderStyle: 'double',
    rotationDuration: 50,
    rotationDirection: -1,
  },
];
