import { OrbitInfo, BlankOrbit } from './types'

export const blankOrbits: BlankOrbit[] = [
  {
    radius: 85,
    gravityFactor: 1.6,
    color: '#00d4ff',
    borderStyle: 'dotted',
    borderWidth: 1,
    rotationDuration: 25,
    rotationDirection: -1,
    opacity: 0.2,
  },
  {
    radius: 145,
    gravityFactor: 1.35,
    color: '#00ffaa',
    borderStyle: 'dashed',
    borderWidth: 1,
    rotationDuration: 35,
    rotationDirection: 1,
    opacity: 0.15,
  },
  {
    radius: 205,
    gravityFactor: 1.0,
    color: '#ff00ff',
    borderStyle: 'dashed',
    borderWidth: 2,
    rotationDuration: 45,
    rotationDirection: -1,
    opacity: 0.2,
    className: 'dash-large',
  },
  {
    radius: 275,
    gravityFactor: 0.65,
    color: '#a855f7',
    borderStyle: 'dashed',
    borderWidth: 2,
    rotationDuration: 55,
    rotationDirection: 1,
    opacity: 0.15,
    className: 'dash-xlarge',
  },
  {
    radius: 385,
    gravityFactor: 0.35,
    color: '#6366f1',
    borderStyle: 'dashed',
    borderWidth: 1,
    rotationDuration: 65,
    rotationDirection: -1,
    opacity: 0.1,
  },
]

export const orbitData: OrbitInfo[] = [
  {
    category: 'Identity',
    icon: '👤',
    info: {
      Name: 'Your Name',
      Location: 'City, Country',
      Email: 'your@email.com',
      Phone: '+1 234 567 890',
    },
    radius: 120,
    gravityFactor: 1.5,
    color: '#00d4ff',
    borderStyle: 'solid',
    rotationDuration: 20,
    rotationDirection: 1,
  },
  {
    category: 'Technology',
    icon: '💻',
    info: {
      Languages: 'TypeScript, Python, Java',
      Frontend: 'React, Angular, Vue',
      Backend: 'Node.js, .NET, Spring',
      Database: 'PostgreSQL, MongoDB',
    },
    radius: 180,
    gravityFactor: 1.2,
    color: '#00ffaa',
    borderStyle: 'dashed',
    rotationDuration: 30,
    rotationDirection: -1,
  },
  {
    category: 'Certifications',
    icon: '📜',
    info: {
      'AWS Solutions Architect': '2023',
      'Azure Developer Associate': '2022',
      'Google Cloud Professional': '2023',
    },
    radius: 250,
    gravityFactor: 0.8,
    color: '#ff00ff',
    borderStyle: 'dotted',
    rotationDuration: 40,
    rotationDirection: 1,
  },
  {
    category: 'Achievements',
    icon: '🏆',
    info: {
      'Best Innovation Award': 'Tech Conference 2023',
      'Open Source Contributor': '500+ contributions',
      'Tech Lead': 'Team of 8 engineers',
    },
    radius: 330,
    gravityFactor: 0.5,
    color: '#a855f7',
    borderStyle: 'double',
    rotationDuration: 50,
    rotationDirection: -1,
  },
]
